services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eramus_backend_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./eramus_backend
    command: bash -c "sleep 5 && bundle exec rails db:create db:schema:load db:seed && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/eramus_backend_development
      RAILS_ENV: development
      RAILS_MASTER_KEY: 3afdb1086e0389ff454383105357adee
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./eramus_frontend
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data: